apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-string
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: faysalmehedi/generate-string
